spring:
  datasource:
    url: jdbc:mysql://localhost:3308/main_db
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  altdb:
    datasource:
      url: jdbc:mysql://localhost:3307/alt_db
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.jdbc.Driver